---
default_user: "ansible"

# Project
project_name: "aircraft-utilization"
project_path: "/opt/{{ project_name }}/{{ env }}"

# Deploy
deploy_branch: "{{ lookup('env', 'DEPLOY_BRANCH') }}"

# Domain records
default_hosted_zone: "kelvedler.dev"

# LetsEncrypt
letsencrypt_email: "hnflkmvjcm@gmail.com"

# Docker images
docker_image_traefik: "traefik:2.11.2"
docker_image_etl: "kelvedler/aircraft-utilization-etl"
docker_image_mongo: "mongo:7.0.7-jammy"
docker_image_postgres: "postgres:15.4-alpine3.18"
docker_image_redis: "redis:7.2.0-alpine3.18"

# Docker containers
docker_etl_name: "etl"

# Docker compose project name
compose_project_name: "{{ project_name }}-{{ env }}"

# Traefik
traefik_path: "/opt/traefik"
traefik_network_name: "traefik-pub-net"
traefik_compose_project_name: "traefik"

# OpenSky Network
opensky_auth: "{{ lookup('env', 'OPENSKY_AUTH') }}"

# ETL settings
etl_repository: "https://github.com/Kelvedler/AircraftUtilization-ETL" 
etl_pythonpath: "/app"
etl_s3_region: "{{ lookup('env', 'ETL_S3_REGION') }}"
etl_s3_role_arn: "{{ lookup('env', 'ETL_S3_ROLE_ARN') }}"
etl_s3_bucket: "{{ lookup('env', 'ETL_S3_BUCKET') }}"
etl_s3_profile_arn: "{{ lookup('env', 'ETL_S3_PROFILE_ARN') }}"
etl_s3_trust_anchor_arn: "{{ lookup('env', 'ETL_S3_TRUST_ANCHOR_ARN') }}"
etl_s3_certificate: "client.crt" 
etl_s3_private_key: "client.key"
etl_cert_path: "/app/certs"
etl_log_level: "INFO"
etl_log_volume_dir: "etl/log"
etl_cert_volume_dir: "etl/certs"
etl_dag_processor_manager_log_location: "/var/log/airflow/dag_processor_manager/dag_processor_manager.log"
etl_airflow_home: "/app/airflow"
etl_airflow_core_dags_folder: "/app/dags"
etl_airflow_core_executor: "CeleryExecutor"
etl_airflow_core_load_examples: false
etl_airflow_core_plugins_folder: "/app/plugins"
etl_airflow_base_log_folder: "/var/log/airflow"
etl_airflow_webserver_config_file: "/app/airflow/webserver_config.py"
etl_airflow_webserver_port: 8000
etl_airflow_scheduler_child_process_log_directory: "/var/log/airflow/scheduler"
etl_secret_key: "{{ lookup('env', 'ETL_SECRET_KEY') }}"

# Mongo
mongo_service: "mongo"
mongo_port: 27017
mongo_user: "{{ lookup('env', 'MONGO_USER') }}"
mongo_pass: "{{ lookup('env', 'MONGO_PASS') }}"

# Postgres etl
postgres_etl_name: "{{ project_name }}-{{ env }}"
postgres_etl_service: "postgres-etl"
postgres_etl_port: 5432
postgres_etl_user: "{{ lookup('env', 'POSTGRES_ETL_USER') }}"
postgres_etl_pass: "{{ lookup('env', 'POSTGRES_ETL_PASS') }}"

# Postgres backend
postgres_backend_name: "{{ project_name }}-{{ env }}"
postgres_backend_service: "postgres-backend"
postgres_backend_port: 5433
postgres_backend_user: "{{ lookup('env', 'POSTGRES_BACKEND_USER') }}"
postgres_backend_pass: "{{ lookup('env', 'POSTGRES_BACKEND_PASS') }}"

# Redis
redis_service: "redis"
redis_port: 6379
